# fly.toml app configuration file generated for sukalov-phonebook-server on 2023-05-22T17:34:31-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sukalov-phonebook-server"
primary_region = "ams"

[env]
  PORT = "3000" 

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
