//commands can be activated using VSCode REST Client extension

### 1. get all persons
GET http://localhost:3001/api/persons


### 3. add Super Mario with bad number
POST http://localhost:3001/api/persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0N2U2YWMxYWIzNjg4M2U3ZGI5ZDcwYiIsImlhdCI6MTY4NjAxOTI5MH0.60rYc8CCbGtbw7LM9dKBMSpjc-iqf7g9A8swt1LvgDE

{
    "name": "Super Mario",
    "number": "231-000-0100"
}

### 3. add Super Mario with bad number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Super Mario",
    "number": "231-000-0100"
}

###
DELETE http://localhost:3001/api/persons/647e5f862b67f6802839982d

### update Dan with malformated data
PUT http://localhost:3001/api/persons/64767157a65ec483d2b0c2f5
Content-Type: application/json

{
    "name": "Daf",
    "number": "231-000-0000"
}

### update with Dan Abramov with GOOD data
PUT http://localhost:3001/api/persons/64767157a65ec483d2b0c2f5
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": "231-090-0109"
}

### empty POST to cause error 400
POST  http://localhost:3001/api/persons

### getting error 404
GET http://localhost:3001/api/persons/foo

### get Dan Abramov 
GET http://localhost:3001/api/persons/64767157a65ec483d2b0c2f5

### getting error 404 2
GET http://localhost:3001/api/foo
